CREATE TABLE IF NOT EXISTS app_user (
 id SERIAL PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role_id INTEGER NOT NULL,
 CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES
role(id)
);
